# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main DirectoryList: ./src
# Target is ????? ../bin/ftpclient

FORMS += ftpclientwindow.ui 
HEADERS += ftpclient.h \
           ftpclientwindow.h 
SOURCES += ftpclient.cpp \
           ftpclientwindow.cpp \
           main.cpp 
QT += network
RESOURCES = ftp.qrc
TARGET=../bin/ftpclient
